
#include "Timer_Lib.h"


void Timer4_Init()
{
	RCC->APB2ENR |= RCC_APB2ENR_IOPBEN | RCC_APB2ENR_AFIOEN;
	RCC->APB1ENR |= RCC_APB1ENR_TIM4EN;
	
	
	GPIOB->CRL |= GPIO_CRL_MODE6;
	
	GPIOB->CRL &= ~GPIO_CRL_CNF6;
	GPIOB->CRL |= GPIO_CRL_CNF6_1;
	
	
	TIM4->BDTR |= TIM_BDTR_MOE;
	
	TIM4->PSC = 1440;
	
    TIM4->ARR = 1000;
		
	TIM4->CCER |= TIM_CCER_CC1E;
	TIM4->CCER &= ~TIM_CCER_CC1P;
	
    TIM4->CCMR1 |= TIM_CCMR1_OC1M_2 | TIM_CCMR1_OC1M_1; 
	
	TIM4->CR1 &= ~TIM_CR1_DIR;
	
	TIM4->CR1 &= ~TIM_CR1_CMS;
	
	TIM4->CR1 |= TIM_CR1_CEN;
	
	TIM4->CCR1 = 75;
}